# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 668e9bf6ca0d57a095500a0f5405f6424c469fe7e7b6982a3e551a1c22b8661224b18ecc6a0c7bce54300e2d28b2a4f700cb3a17873137e307a69a30d17d86a5

test:
  secret_key_base: 94e5e65ce99dd27e43740c9df42cb631bf48e613b4b1f44229f6b486ecc376ec90ef76b37768114cd866216a64352e721ad6d2d40e28a3ca04d1039ac3e810dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
